
import React from 'react';
import { RemedyResponse } from '../types';

interface RemedyDisplayProps {
  remedy: RemedyResponse;
}

const RemedyDisplay: React.FC<RemedyDisplayProps> = ({ remedy }) => {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-6 duration-700 space-y-10">
      {/* Report Header */}
      <div className="bg-white border border-slate-200 rounded-[3rem] p-10 shadow-2xl shadow-slate-200 overflow-hidden relative">
        <div className="relative z-10 flex flex-col md:flex-row gap-8 items-start md:items-center">
          <div className="w-20 h-20 bg-slate-900 rounded-3xl flex items-center justify-center text-4xl shadow-xl shadow-slate-200">
            📑
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[10px] font-black bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded uppercase tracking-widest">Diagnostic Summary</span>
              <span className="text-slate-300 text-xs">Generated by HealAI v2.5</span>
            </div>
            <h2 className="text-4xl font-black text-slate-900 mb-3 tracking-tight">{remedy.condition}</h2>
            <p className="text-slate-500 leading-relaxed font-medium max-w-2xl text-lg">{remedy.summary}</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Treatment Protocol */}
        <ReportSection 
          title="Clinical Home Remedies" 
          items={remedy.homeRemedies} 
          icon="🧪" 
          theme="emerald" 
        />

        {/* Rapid Relief */}
        <ReportSection 
          title="Immediate Interventions" 
          items={remedy.quickSolutions} 
          icon="⚡" 
          theme="amber" 
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Preventive Measures */}
        <ReportSection 
          title="Preventive Guidelines" 
          items={remedy.safetyPrecautions} 
          icon="🛡️" 
          theme="blue" 
        />

        {/* Escalation Signs */}
        <ReportSection 
          title="Clinical Red Flags" 
          items={remedy.whenToSeeDoctor} 
          icon="🩺" 
          theme="rose" 
          isWarning
        />
      </div>

      {/* Footer Note */}
      <div className="bg-slate-900 text-white rounded-[2.5rem] p-10 flex flex-col md:flex-row gap-10 items-center justify-between">
        <div className="max-w-xl">
          <h4 className="font-bold text-2xl mb-4">Patient Information Security</h4>
          <p className="text-slate-400 text-sm leading-relaxed font-medium">
            This information is provided for educational purposes based on current clinical literature. HealAI does not store your specific diagnostic data without your explicit consent.
          </p>
        </div>
        <button className="whitespace-nowrap px-8 py-4 bg-white text-slate-900 font-black rounded-2xl hover:bg-slate-100 transition-all shadow-xl">Print Health Report</button>
      </div>
    </div>
  );
};

const ReportSection: React.FC<{ title: string, items: string[], icon: string, theme: 'emerald' | 'amber' | 'blue' | 'rose', isWarning?: boolean }> = ({ title, items, icon, theme, isWarning }) => {
  const themes = {
    emerald: "bg-white border-emerald-100/50 text-emerald-900 shadow-emerald-100/20",
    amber: "bg-white border-amber-100/50 text-amber-900 shadow-amber-100/20",
    blue: "bg-white border-blue-100/50 text-blue-900 shadow-blue-100/20",
    rose: "bg-white border-rose-100/50 text-rose-900 shadow-rose-100/20"
  };

  const iconColors = {
    emerald: "bg-emerald-50 text-emerald-600",
    amber: "bg-amber-50 text-amber-600",
    blue: "bg-blue-50 text-blue-600",
    rose: "bg-rose-50 text-rose-600"
  };

  return (
    <div className={`rounded-[2.5rem] border p-10 shadow-xl transition-all hover:-translate-y-1 duration-300 ${themes[theme]}`}>
      <div className="flex items-center gap-4 mb-8">
        <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-xl shadow-inner ${iconColors[theme]}`}>
          {icon}
        </div>
        <h3 className="font-extrabold text-xl tracking-tight">{title}</h3>
      </div>
      <ul className="space-y-6">
        {items.map((item, i) => (
          <li key={i} className="flex gap-4 items-start">
            <div className={`mt-2.5 w-1.5 h-1.5 rounded-full flex-shrink-0 ${isWarning ? 'bg-rose-500' : 'bg-slate-300'}`}></div>
            <span className="text-slate-600 text-base leading-relaxed font-medium">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default RemedyDisplay;